In [43]:
!pip install numpy
!pip install pandas

In [44]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split  

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [45]:
# Let's start by naming the features
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [46]:
# Reading the dataset through pandas function
iris_data = pd.read_csv( url , names = names )
print(iris_data)

     sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [47]:
# Analyzing the table 
iris_data_analyze = iris_data.info()
print(iris_data_analyze)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal-length  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3   petal-width   150 non-null    float64
 4   Class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [48]:
# Checking for missing values 
missing_values = iris_data.isnull().sum()
print(missing_values)

sepal-length    0
sepal-width     0
petal-length    0
petal-width     0
Class           0
dtype: int64


In [49]:
# Assigning the inputs with feature variables
inputs = iris_data.drop(columns = ['Class'])
# Assigning the outputs with targret variables 
outputs = iris_data['Class']

In [53]:
# Displaying the top section of inputs 
inputs.head()

sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [58]:
# Displaying the top section of outputs 
outputs.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Class, dtype: object

In [61]:
# Converting into one dimensinol numpy array using numpy 
outputs_1d = outputs.values

In [63]:
# Converting non-numerical values into numerical values using LabelEncoder
# Outputs(target variables) data structure is object type
le = preprocessing.LabelEncoder()
outputs_encoded = le.fit_transform(outputs_1d)
# Displaying the converted values 
print(outputs_encoded)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [65]:
# Spliting dataset for training(80%) and testing(20%)
inputs_train, inputs_test, outputs_encoded_train, outputs_encoded_test = train_test_split(inputs, outputs_encoded, test_size = 0.20)


In [67]:
# Normalizing the inputs data for both training and testing 
# Target variables are not normalized
# For Normalization we are using standardization(Z-score normalization) 
# Initialing the scaler
scaler = preprocessing.StandardScaler()
# Scalering the inputs data (features variables) of training 
inputs_train_normalized = scaler.fit_transform(inputs_train)
# Scalering the inputs data (features variables) of testing 
inputs_test_normalized = scaler.fit_transform(inputs_test)
# Displaying the size of Normalized data for training
print(inputs_train_normalized.size)
# Displaying the size of Normalized data for testing
print(inputs_test_normalized.size)

480
120


In [100]:
# Define the Activation function: we are using Sigmoid 

# Define the Sigmoid activation function
def sigmoid(inputs):
    inputs = np.clip(inputs, -500, 500)  # Clipping the input range
    return 1 / (1 + np.exp(-inputs))

# Define the derivative of Sigmoid for backpropagation
def sigmoid_derivative(inputs):
    inputs = np.clip(inputs, -500, 500)  # Clipping the input range
    return inputs * (1 - inputs)


In [71]:
# Designing the MLP model
# Our MLP model will consist of three hidden layers
class MLP():
    def __init__(self, input_size, h1_ly_size, h2_ly_size, h3_ly_size, output_size):
        
        # Designing the layer 
        # Initialize weights and biases for input to hidden layer 1
        self.wt_input_h1_size = np.random.randn(input_size, h1_ly_size)
        self.bais_h1 = np.zeros((1, h1_ly_size))

        # Initialize weights and biases for hidden layer 1 to hidden layer 2
        self.wt_h1_h2_size = np.random.randn(h1_ly_size, h2_ly_size)
        self.bais_h2 = np.zeros((1, h2_ly_size))

        
        # Initialize weights and biases for hidden layer 2 to hidden layer 3
        self.wt_h2_h3_size = np.random.randn(h2_ly_size, h3_ly_size)
        self.bais_h3 = np.zeros((1, h3_ly_size))

        # Initialize weights and biases for hidden layer 3 to output layer
        self.wt_h3_output_size = np.random.randn(h3_ly_size, output_size)
        self.bais_outputs = np.zeros((1, output_size))
        
    # Calculation method for forward chaining 
    def forwardfeeding(self, input):
        # Calculating the h1 layer by passing inputs
        self.computed_h1 = np.dot(input, self.wt_input_h1_size) + self.bais_h1
        self.h1_outputs = sigmoid(self.computed_h1)

        # Calculating the h2 layer by passing h1 layer inputs
        self.computed_h2 = self.h1_outputs.dot(self.wt_h1_h2_size) + self.bais_h2 
        self.h2_outputs = sigmoid(self.computed_h2)
        
        # Calculating the h3 layer by passing h2 layer inputs
        self.computed_h3 = np.dot(self.h2_outputs, self.wt_h2_h3_size) + self.bais_h3
        self.h3_outputs = sigmoid(self.computed_h3)
        
         # Calculating the output layer by passing h3 layer inputs
        self.computed_output= np.dot(self.h3_outputs, self.wt_h3_output_size) + self.bais_outputs
        output = sigmoid(self.computed_output)

        return output
        
    # Calculation method for backward chaining and loss
    def backwardfeeding(self, input, output, fw_output, learning_rate):

        # Converting the dimension
        reshape_output = output.reshape(output.size,1)    
        
        # Calculate the error in the output
        output_error = fw_output - reshape_output

        # Calculate the error, delta weights and delta bais for hidden layer 3
        d_weights3 = self.h3_outputs.T.dot(output_error * sigmoid_derivative(self.computed_output))
        d_bias3 = np.sum(output_error * sigmoid_derivative(self.computed_output), axis=0, keepdims=True)
        error_hidden_h3 = output_error.dot(self.wt_h3_output_size.T) * sigmoid_derivative(self.computed_h3)

        # Calculate the error, delta weights and delta bais for hidden layer 2
        d_weights2 = self.h2_outputs.T.dot(error_hidden_h3 * sigmoid_derivative(self.computed_h3))
        d_bias2 = np.sum(error_hidden_h3 * sigmoid_derivative(self.computed_h3), axis=0, keepdims=True)
        error_hidden_h2 = error_hidden_h3.dot(self.wt_h2_h3_size.T) * sigmoid_derivative(self.computed_h2)

        # Calculate the error, delta weights and delta bais for hidden layer 1
        d_weights1 = self.h1_outputs.T.dot(error_hidden_h2 * sigmoid_derivative(self.computed_h2))
        d_bias1 = np.sum(error_hidden_h2 * sigmoid_derivative(self.computed_h2), axis=0, keepdims=True)
        error_hidden_h1 = error_hidden_h2.dot(self.wt_h1_h2_size.T) * sigmoid_derivative(self.computed_h1)
        
        # Calculate the delta weights and delta bais for input 
        d_weights = input.T.dot(error_hidden_h1)
        d_bias = np.sum(error_hidden_h1, axis=0, keepdims=True)

        # Update weights and biases
        self.wt_h3_output_size -= learning_rate * d_weights3
        self.bais_outputs -= learning_rate * d_bias3
        self.wt_h2_h3_size -= learning_rate * d_weights2
        self.bais_h3 -= learning_rate * d_bias2
        self.wt_h1_h2_size -= learning_rate * d_weights1
        self.bais_h2 -= learning_rate * d_bias1
        self.wt_input_h1_size -= learning_rate * d_weights
        self.bais_h1 -= learning_rate * d_bias
       
        


        

In [73]:
# Defining the training method
def training_MLP(model, input, output, iteration, learning_rate):
    for iteration in range(iteration):
        # Forward passing 
        fw_output = model.forwardfeeding(input)
        # Backward passing and updating weights and bais
        model.backwardfeeding(input, output, fw_output, learning_rate)

        if (iteration+1) % 100 == 0:
            loss = np.mean((output.reshape(output.size,1)- fw_output) ** 2)
            print(f'iteration {iteration+1}, Loss: {loss:.4f}')

In [75]:
# For this model, initialing
# inputs size will number of features
# Three hidden layer with 14,7,3 nodes
# output_size wii be one
# For evaluation purpose with other model this values are used
input_size = inputs_train_normalized.shape[1] # counting the number of features
hidden_layer1 = 14
hidden_layer2 = 7
hidden_layer3 = 3
output_size = 3
model = MLP(input_size, hidden_layer1, hidden_layer2, hidden_layer3, output_size)

In [94]:
# Training the model 
# Call the method
training_MLP(model, inputs_train_normalized, outputs_encoded_train, 100, 0.01)

iteration 100, Loss: 1.3446


In [96]:
# Evaluate the trained MLP with test data 
predicted_outputs = model.forwardfeeding(inputs_test_normalized)
print(predicted_outputs)

# Binary predictions for classification
binary_predicted_outputs = np.round(predicted_outputs)

print(binary_predicted_outputs.shape[0])
print(binary_predicted_outputs)

[[7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-218 7.31058579e-001]
 [7.12457641e-218 7.12457641e-2

In [98]:
# Evaluating the model
# Compute accuracy (percentage of correct predictions)
accuracy = np.mean(binary_predicted_outputs == outputs_encoded_test.reshape(outputs_encoded_test.size,1))
print(f"Accuracy: {accuracy:.2f}")


Accuracy: 0.30
